<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LawyerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        
        $lawyers = [
            ['id' => 1, 'name' => 'Harvey Specter', 'location' => 'Chicago', 'service' => 'Tax Policy', 'type_of_law' => 'Tax law', 'total_cases' => 300, 'winning_rate' => 0.95],
            ['id' => 2, 'name' => 'Mike Ross', 'location' => 'New York', 'service' => 'Real Estate Finance', 'type_of_law' => 'Real Estate law', 'total_cases' => 150, 'winning_rate' => 0.88],
            ['id' => 3, 'name' => 'Jessica Pearson', 'location' => 'Los Angeles', 'service' => 'Accounting Fraud', 'type_of_law' => 'Criminal law', 'total_cases' => 450, 'winning_rate' => 0.92],
            ['id' => 4, 'name' => 'Louis Litt', 'location' => 'Austin', 'service' => 'Insurance Litigation', 'type_of_law' => 'Insurance law', 'total_cases' => 200, 'winning_rate' => 0.81],
            ['id' => 5, 'name' => 'Rachel Zane', 'location' => 'Chicago', 'service' => 'Tax Policy', 'type_of_law' => 'Tax law', 'total_cases' => 350, 'winning_rate' => 0.79],
            ['id' => 6, 'name' => 'Donna Paulsen', 'location' => 'New York', 'service' => 'Real Estate Finance', 'type_of_law' => 'Real Estate law', 'total_cases' => 220, 'winning_rate' => 0.85],
            ['id' => 7, 'name' => 'Robert Zane', 'location' => 'Los Angeles', 'service' => 'Accounting Fraud', 'type_of_law' => 'Criminal law', 'total_cases' => 400, 'winning_rate' => 0.87],
            ['id' => 8, 'name' => 'Daniel Hardman', 'location' => 'Austin', 'service' => 'Insurance Litigation', 'type_of_law' => 'Insurance law', 'total_cases' => 320, 'winning_rate' => 0.83],
            ['id' => 9, 'name' => 'Katrina Bennett', 'location' => 'Chicago', 'service' => 'Tax Policy', 'type_of_law' => 'Tax law', 'total_cases' => 275, 'winning_rate' => 0.80],
            ['id' => 10, 'name' => 'Alex Williams', 'location' => 'New York', 'service' => 'Real Estate Finance', 'type_of_law' => 'Real Estate law', 'total_cases' => 180, 'winning_rate' => 0.77],
            ['id' => 11, 'name' => 'Carl Jenkins', 'location' => 'Chicago', 'service' => 'Tax Policy', 'type_of_law' => 'Tax law', 'total_cases' => 325, 'winning_rate' => 0.74],
            ['id' => 12, 'name' => 'Susan Boyle', 'location' => 'New York', 'service' => 'Accounting Fraud', 'type_of_law' => 'Criminal law', 'total_cases' => 210, 'winning_rate' => 0.69],
            ['id' => 13, 'name' => 'Anthony Stark', 'location' => 'Los Angeles', 'service' => 'Real Estate Finance', 'type_of_law' => 'Real Estate law', 'total_cases' => 528, 'winning_rate' => 0.82],
            ['id' => 14, 'name' => 'Melissa Warren', 'location' => 'Austin', 'service' => 'Insurance Litigation', 'type_of_law' => 'Insurance law', 'total_cases' => 115, 'winning_rate' => 0.67],
            ['id' => 15, 'name' => 'Roger Stevens', 'location' => 'Chicago', 'service' => 'Tax Policy', 'type_of_law' => 'Tax law', 'total_cases' => 980, 'winning_rate' => 0.94],
            ['id' => 16, 'name' => 'Natalie Portman', 'location' => 'New York', 'service' => 'Accounting Fraud', 'type_of_law' => 'Criminal law', 'total_cases' => 450, 'winning_rate' => 0.61],
            ['id' => 17, 'name' => 'Oliver Queen', 'location' => 'Los Angeles', 'service' => 'Real Estate Finance', 'type_of_law' => 'Real Estate law', 'total_cases' => 375, 'winning_rate' => 0.78],
            ['id' => 18, 'name' => 'Diana Prince', 'location' => 'Austin', 'service' => 'Insurance Litigation', 'type_of_law' => 'Insurance law', 'total_cases' => 230, 'winning_rate' => 0.86],
            ['id' => 19, 'name' => 'Peter Parker', 'location' => 'Chicago', 'service' => 'Tax Policy', 'type_of_law' => 'Tax law', 'total_cases' => 640, 'winning_rate' => 0.72],
            ['id' => 20, 'name' => 'Bruce Wayne', 'location' => 'New York', 'service' => 'Accounting Fraud', 'type_of_law' => 'Criminal law', 'total_cases' => 800, 'winning_rate' => 0.97],
            ['id' => 21, 'name' => 'Clark Kent', 'location' => 'Los Angeles', 'service' => 'Real Estate Finance', 'type_of_law' => 'Real Estate law', 'total_cases' => 487, 'winning_rate' => 0.76],
            ['id' => 22, 'name' => 'Lois Lane', 'location' => 'Austin', 'service' => 'Insurance Litigation', 'type_of_law' => 'Insurance law', 'total_cases' => 320, 'winning_rate' => 0.63],
            ['id' => 23, 'name' => 'Lex Luthor', 'location' => 'Chicago', 'service' => 'Tax Policy', 'type_of_law' => 'Tax law', 'total_cases' => 540, 'winning_rate' => 0.88],
            ['id' => 24, 'name' => 'Barry Allen', 'location' => 'New York', 'service' => 'Accounting Fraud', 'type_of_law' => 'Criminal law', 'total_cases' => 275, 'winning_rate' => 0.90],
            ['id' => 25, 'name' => 'Hal Jordan', 'location' => 'Los Angeles', 'service' => 'Real Estate Finance', 'type_of_law' => 'Real Estate law', 'total_cases' => 650, 'winning_rate' => 0.71],
            ['id' => 26, 'name' => 'Arthur Curry', 'location' => 'Austin', 'service' => 'Insurance Litigation', 'type_of_law' => 'Insurance law', 'total_cases' => 405, 'winning_rate' => 0.85],
            ['id' => 27, 'name' => 'Billy Batson', 'location' => 'Chicago', 'service' => 'Tax Policy', 'type_of_law' => 'Tax law', 'total_cases' => 222, 'winning_rate' => 0.84],
            ['id' => 28, 'name' => 'John Stewart', 'location' => 'New York', 'service' => 'Accounting Fraud', 'type_of_law' => 'Criminal law', 'total_cases' => 389, 'winning_rate' => 0.79],
            ['id' => 29, 'name' => 'Selina Kyle', 'location' => 'Los Angeles', 'service' => 'Real Estate Finance', 'type_of_law' => 'Real Estate law', 'total_cases' => 560, 'winning_rate' => 0.68],
            ['id' => 30, 'name' => 'Pamela Isley', 'location' => 'Austin', 'service' => 'Insurance Litigation', 'type_of_law' => 'Insurance law', 'total_cases' => 310, 'winning_rate' => 0.82],
            ['id' => 31, 'name' => 'Harleen Quinzel', 'location' => 'Chicago', 'service' => 'Tax Policy', 'type_of_law' => 'Tax law', 'total_cases' => 190, 'winning_rate' => 0.77],
            ['id' => 32, 'name' => 'Oswald Cobblepot', 'location' => 'New York', 'service' => 'Accounting Fraud', 'type_of_law' => 'Criminal law', 'total_cases' => 340, 'winning_rate' => 0.66],
            ['id' => 33, 'name' => 'Edward Nygma', 'location' => 'Los Angeles', 'service' => 'Real Estate Finance', 'type_of_law' => 'Real Estate law', 'total_cases' => 430, 'winning_rate' => 0.92],
            ['id' => 34, 'name' => 'Jonathan Crane', 'location' => 'Austin', 'service' => 'Insurance Litigation', 'type_of_law' => 'Insurance law', 'total_cases' => 280, 'winning_rate' => 0.89],
            ['id' => 35, 'name' => 'Carmine Falcone', 'location' => 'Chicago', 'service' => 'Tax Policy', 'type_of_law' => 'Tax law', 'total_cases' => 470, 'winning_rate' => 0.74],
            ['id' => 36, 'name' => 'Harvey Dent', 'location' => 'New York', 'service' => 'Accounting Fraud', 'type_of_law' => 'Criminal law', 'total_cases' => 360, 'winning_rate' => 0.83],
            ['id' => 37, 'name' => "Ra's al Ghul", 'location' => 'Los Angeles', 'service' => 'Real Estate Finance', 'type_of_law' => 'Real Estate law', 'total_cases' => 520, 'winning_rate' => 0.80],
            ['id' => 38, 'name' => 'Kirk Langstrom', 'location' => 'Austin', 'service' => 'Insurance Litigation', 'type_of_law' => 'Insurance law', 'total_cases' => 295, 'winning_rate' => 0.65],
            ['id' => 39, 'name' => 'Floyd Lawton', 'location' => 'Chicago', 'service' => 'Tax Policy', 'type_of_law' => 'Tax law', 'total_cases' => 550, 'winning_rate' => 0.91],
            ['id' => 40, 'name' => 'Slade Wilson', 'location' => 'New York', 'service' => 'Accounting Fraud', 'type_of_law' => 'Criminal law', 'total_cases' => 405, 'winning_rate' => 0.87],
            ['id' => 41, 'name' => 'Linda Carter', 'location' => 'Los Angeles', 'service' => 'Real Estate Finance', 'type_of_law' => 'Real Estate law', 'total_cases' => 467, 'winning_rate' => 0.88],
            ['id' => 42, 'name' => 'Jason Todd', 'location' => 'Austin', 'service' => 'Insurance Litigation', 'type_of_law' => 'Insurance law', 'total_cases' => 238, 'winning_rate' => 0.82],
            ['id' => 43, 'name' => 'Helena Bertinelli', 'location' => 'Chicago', 'service' => 'Tax Policy', 'type_of_law' => 'Tax law', 'total_cases' => 159, 'winning_rate' => 0.73],
            ['id' => 44, 'name' => 'Ray Palmer', 'location' => 'New York', 'service' => 'Accounting Fraud', 'type_of_law' => 'Criminal law', 'total_cases' => 320, 'winning_rate' => 0.69],
            ['id' => 45, 'name' => 'Dinah Lance', 'location' => 'Los Angeles', 'service' => 'Real Estate Finance', 'type_of_law' => 'Real Estate law', 'total_cases' => 586, 'winning_rate' => 0.92],
            ['id' => 46, 'name' => 'Oliver Queen', 'location' => 'Austin', 'service' => 'Insurance Litigation', 'type_of_law' => 'Insurance law', 'total_cases' => 410, 'winning_rate' => 0.85],
            ['id' => 47, 'name' => 'Thomas Wayne', 'location' => 'Chicago', 'service' => 'Tax Policy', 'type_of_law' => 'Tax law', 'total_cases' => 275, 'winning_rate' => 0.64],
            ['id' => 48, 'name' => 'Martha Wayne', 'location' => 'New York', 'service' => 'Accounting Fraud', 'type_of_law' => 'Criminal law', 'total_cases' => 389, 'winning_rate' => 0.78],
            ['id' => 49, 'name' => 'Kara Zor-El', 'location' => 'Los Angeles', 'service' => 'Real Estate Finance', 'type_of_law' => 'Real Estate law', 'total_cases' => 460, 'winning_rate' => 0.81],
            ['id' => 50, 'name' => "J'onn J'onzz", 'location' => 'Austin', 'service' => 'Insurance Litigation', 'type_of_law' => 'Insurance law', 'total_cases' => 222, 'winning_rate' => 0.76],
            ['id' => 51, 'name' => 'Ted Kord', 'location' => 'Chicago', 'service' => 'Tax Policy', 'type_of_law' => 'Tax law', 'total_cases' => 198, 'winning_rate' => 0.81],
            ['id' => 52, 'name' => 'Michael Holt', 'location' => 'New York', 'service' => 'Accounting Fraud', 'type_of_law' => 'Criminal law', 'total_cases' => 340, 'winning_rate' => 0.89],
            ['id' => 53, 'name' => 'Adrian Chase', 'location' => 'Los Angeles', 'service' => 'Real Estate Finance', 'type_of_law' => 'Real Estate law', 'total_cases' => 412, 'winning_rate' => 0.67],
            ['id' => 54, 'name' => 'Renee Montoya', 'location' => 'Austin', 'service' => 'Insurance Litigation', 'type_of_law' => 'Insurance law', 'total_cases' => 288, 'winning_rate' => 0.84],
            ['id' => 55, 'name' => 'Kate Kane', 'location' => 'Chicago', 'service' => 'Tax Policy', 'type_of_law' => 'Tax law', 'total_cases' => 475, 'winning_rate' => 0.79],
            ['id' => 56, 'name' => 'Cassandra Cain', 'location' => 'New York', 'service' => 'Accounting Fraud', 'type_of_law' => 'Criminal law', 'total_cases' => 364, 'winning_rate' => 0.92],
            ['id' => 57, 'name' => 'Stephanie Brown', 'location' => 'Los Angeles', 'service' => 'Real Estate Finance', 'type_of_law' => 'Real Estate law', 'total_cases' => 522, 'winning_rate' => 0.87],
            ['id' => 58, 'name' => 'Tim Drake', 'location' => 'Austin', 'service' => 'Insurance Litigation', 'type_of_law' => 'Insurance law', 'total_cases' => 299, 'winning_rate' => 0.65],
            ['id' => 59, 'name' => 'Damian Wayne', 'location' => 'Chicago', 'service' => 'Tax Policy', 'type_of_law' => 'Tax law', 'total_cases' => 543, 'winning_rate' => 0.83],
            ['id' => 60, 'name' => 'Dick Grayson', 'location' => 'New York', 'service' => 'Accounting Fraud', 'type_of_law' => 'Criminal law', 'total_cases' => 278, 'winning_rate' => 0.72],
            ['id' => 61, 'name' => 'Bette Kane', 'location' => 'Los Angeles', 'service' => 'Real Estate Finance', 'type_of_law' => 'Real Estate law', 'total_cases' => 305, 'winning_rate' => 0.68],
            ['id' => 62, 'name' => 'Garfield Logan', 'location' => 'Austin', 'service' => 'Insurance Litigation', 'type_of_law' => 'Insurance law', 'total_cases' => 480, 'winning_rate' => 0.73],
            ['id' => 63, 'name' => 'Rachel Roth', 'location' => 'Chicago', 'service' => 'Tax Policy', 'type_of_law' => 'Tax law', 'total_cases' => 240, 'winning_rate' => 0.82],
            ['id' => 64, 'name' => "Koriand'r", 'location' => 'New York', 'service' => 'Accounting Fraud', 'type_of_law' => 'Criminal law', 'total_cases' => 360, 'winning_rate' => 0.89],
            ['id' => 65, 'name' => 'Victor Stone', 'location' => 'Los Angeles', 'service' => 'Real Estate Finance', 'type_of_law' => 'Real Estate law', 'total_cases' => 402, 'winning_rate' => 0.76],
            ['id' => 66, 'name' => 'Roy Harper', 'location' => 'Austin', 'service' => 'Insurance Litigation', 'type_of_law' => 'Insurance law', 'total_cases' => 318, 'winning_rate' => 0.80],
            ['id' => 67, 'name' => 'Wally West', 'location' => 'Chicago', 'service' => 'Tax Policy', 'type_of_law' => 'Tax law', 'total_cases' => 489, 'winning_rate' => 0.90],
            ['id' => 68, 'name' => 'Zatanna Zatara', 'location' => 'New York', 'service' => 'Accounting Fraud', 'type_of_law' => 'Criminal law', 'total_cases' => 276, 'winning_rate' => 0.77],
            ['id' => 69, 'name' => 'John Constantine', 'location' => 'Los Angeles', 'service' => 'Real Estate Finance', 'type_of_law' => 'Real Estate law', 'total_cases' => 357, 'winning_rate' => 0.83],
            ['id' => 70, 'name' => 'Oliver Queen', 'location' => 'Austin', 'service' => 'Insurance Litigation', 'type_of_law' => 'Insurance law', 'total_cases' => 420, 'winning_rate' => 0.86],
            ['id' => 71, 'name' => 'Laurel Lance', 'location' => 'Chicago', 'service' => 'Tax Policy', 'type_of_law' => 'Tax law', 'total_cases' => 333, 'winning_rate' => 0.75],
            ['id' => 72, 'name' => 'Tommy Merlyn', 'location' => 'New York', 'service' => 'Accounting Fraud', 'type_of_law' => 'Criminal law', 'total_cases' => 218, 'winning_rate' => 0.64],
            ['id' => 73, 'name' => 'Thalia al Ghul', 'location' => 'Los Angeles', 'service' => 'Real Estate Finance', 'type_of_law' => 'Real Estate law', 'total_cases' => 522, 'winning_rate' => 0.91],
            ['id' => 74, 'name' => 'Nyssa al Ghul', 'location' => 'Austin', 'service' => 'Insurance Litigation', 'type_of_law' => 'Insurance law', 'total_cases' => 309, 'winning_rate' => 0.78],
            ['id' => 75, 'name' => 'Malcolm Merlyn', 'location' => 'Chicago', 'service' => 'Tax Policy', 'type_of_law' => 'Tax law', 'total_cases' => 467, 'winning_rate' => 0.86],
            ['id' => 76, 'name' => 'Moira Queen', 'location' => 'New York', 'service' => 'Accounting Fraud', 'type_of_law' => 'Criminal law', 'total_cases' => 359, 'winning_rate' => 0.81],
            ['id' => 77, 'name' => 'Slade Wilson', 'location' => 'Los Angeles', 'service' => 'Real Estate Finance', 'type_of_law' => 'Real Estate law', 'total_cases' => 414, 'winning_rate' => 0.74],
            ['id' => 78, 'name' => 'Adrian Chase', 'location' => 'Austin', 'service' => 'Insurance Litigation', 'type_of_law' => 'Insurance law', 'total_cases' => 292, 'winning_rate' => 0.79],
            ['id' => 79, 'name' => 'Felicity Smoak', 'location' => 'Chicago', 'service' => 'Tax Policy', 'type_of_law' => 'Tax law', 'total_cases' => 361, 'winning_rate' => 0.82],
            ['id' => 80, 'name' => 'Curtis Holt', 'location' => 'New York', 'service' => 'Accounting Fraud', 'type_of_law' => 'Criminal law', 'total_cases' => 438, 'winning_rate' => 0.88],
            ['id' => 81, 'name' => 'Thea Queen', 'location' => 'Los Angeles', 'service' => 'Real Estate Finance', 'type_of_law' => 'Real Estate law', 'total_cases' => 255, 'winning_rate' => 0.65],
            ['id' => 82, 'name' => 'Roy Harper', 'location' => 'Austin', 'service' => 'Insurance Litigation', 'type_of_law' => 'Insurance law', 'total_cases' => 473, 'winning_rate' => 0.72],
            ['id' => 83, 'name' => 'Quentin Lance', 'location' => 'Chicago', 'service' => 'Tax Policy', 'type_of_law' => 'Tax law', 'total_cases' => 341, 'winning_rate' => 0.76],
            ['id' => 84, 'name' => 'Rory Regan', 'location' => 'New York', 'service' => 'Accounting Fraud', 'type_of_law' => 'Criminal law', 'total_cases' => 422, 'winning_rate' => 0.69],
            ['id' => 85, 'name' => 'Rene Ramirez', 'location' => 'Los Angeles', 'service' => 'Real Estate Finance', 'type_of_law' => 'Real Estate law', 'total_cases' => 510, 'winning_rate' => 0.83],
            ['id' => 86, 'name' => 'Dinah Drake', 'location' => 'Austin', 'service' => 'Insurance Litigation', 'type_of_law' => 'Insurance law', 'total_cases' => 378, 'winning_rate' => 0.81],
            ['id' => 87, 'name' => 'Evelyn Sharp', 'location' => 'Chicago', 'service' => 'Tax Policy', 'type_of_law' => 'Tax law', 'total_cases' => 289, 'winning_rate' => 0.84],
            ['id' => 88, 'name' => 'Ricardo Diaz', 'location' => 'New York', 'service' => 'Accounting Fraud', 'type_of_law' => 'Criminal law', 'total_cases' => 332, 'winning_rate' => 0.71],
            ['id' => 89, 'name' => 'Emiko Queen', 'location' => 'Los Angeles', 'service' => 'Real Estate Finance', 'type_of_law' => 'Real Estate law', 'total_cases' => 417, 'winning_rate' => 0.77],
            ['id' => 91, 'name' => 'Alan Shore', 'location' => 'Chicago', 'service' => 'Insurance Litigation', 'type_of_law' => 'Insurance law', 'total_cases' => 310, 'winning_rate' => 0.76],
            ['id' => 92, 'name' => 'Denny Crane', 'location' => 'New York', 'service' => 'Tax Policy', 'type_of_law' => 'Tax law', 'total_cases' => 220, 'winning_rate' => 0.84],
            ['id' => 93, 'name' => 'Shirley Schmidt', 'location' => 'Los Angeles', 'service' => 'Accounting Fraud', 'type_of_law' => 'Criminal law', 'total_cases' => 420, 'winning_rate' => 0.89],
            ['id' => 94, 'name' => 'Paul Lewiston', 'location' => 'Austin', 'service' => 'Real Estate Finance', 'type_of_law' => 'Real Estate law', 'total_cases' => 390, 'winning_rate' => 0.91],
            ['id' => 95, 'name' => 'Carl Sack', 'location' => 'Chicago', 'service' => 'Insurance Litigation', 'type_of_law' => 'Insurance law', 'total_cases' => 280, 'winning_rate' => 0.78],
            ['id' => 96, 'name' => 'Jeffrey Coho', 'location' => 'New York', 'service' => 'Tax Policy', 'type_of_law' => 'Tax law', 'total_cases' => 230, 'winning_rate' => 0.82],
            ['id' => 97, 'name' => 'Clarence Bell', 'location' => 'Los Angeles', 'service' => 'Accounting Fraud', 'type_of_law' => 'Criminal law', 'total_cases' => 410, 'winning_rate' => 0.86],
            ['id' => 98, 'name' => 'Lori Colson', 'location' => 'Austin', 'service' => 'Real Estate Finance', 'type_of_law' => 'Real Estate law', 'total_cases' => 365, 'winning_rate' => 0.88],
            ['id' => 99, 'name' => 'Brad Chase', 'location' => 'Chicago', 'service' => 'Insurance Litigation', 'type_of_law' => 'Insurance law', 'total_cases' => 295, 'winning_rate' => 0.83],
            ['id' => 100, 'name' => 'Sally Heep', 'location' => 'New York', 'service' => 'Tax Policy', 'type_of_law' => 'Tax law', 'total_cases' => 210, 'winning_rate' => 0.74],
            ];
        DB::table('lawyers')->insert($lawyers);
    }
}
